### ISSUE TITLE
Environment variable in CMakeLists.txt

### ISSUE THREAD

**Issue by antoinejoly** [Azrael3000/Crixus#1]
Hey Arno,

In your CMakeLists.txt you have the following environment variable:

set(ENV{HDF5_ROOT} "/home/arnom/software/shdf5")

Through this variable you force users to have HDF5 installed locally and the directory to be given, however it might be better to comment this line.

This is because HDF5 can be downloaded through apt-get (by downloading libhdf5-serial-dev), and in this case it isn't necessary to set this environment variable.

I think it will be better to leave this commented and add a troubleshooting section in your INSTALL file explaining how to modify the CMakeLists.txt file if necessary.

**Comment by Azrael3000** [comment]
Thanks Antoine. That sounds like a sensible idea. I will try and do that soon.

**Comment by Azrael3000** [comment]
Resolved in 3238b0e and e1c7fd1
